# Generated by Django 3.2.3 on 2021-05-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='port_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'port_number',
            },
        ),
        migrations.CreateModel(
            name='Profile_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_name', models.CharField(default='', max_length=100)),
                ('contact_name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('port', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
