# Generated by Django 3.2.3 on 2021-05-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_table',
            old_name='bussiness_name',
            new_name='street',
        ),
    ]
