# Generated by Django 3.2.3 on 2021-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportApp', '0002_rename_bussiness_name_profile_table_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_table',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile_table',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile_table',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile_table',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
