# Generated by Django 3.2.3 on 2021-05-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportApp', '0003_auto_20210519_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_table',
            name='downloadSpeed',
            field=models.IntegerField(default=0),
        ),
    ]
