# Generated by Django 3.2.3 on 2021-05-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportApp', '0004_profile_table_downloadspeed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_table',
            old_name='street',
            new_name='bussiness_name',
        ),
    ]
