# Generated by Django 3.2.3 on 2021-05-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportApp', '0005_rename_street_profile_table_bussiness_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_table',
            old_name='address',
            new_name='streets',
        ),
    ]
