# Generated by Django 3.2.3 on 2021-05-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportApp', '0006_rename_address_profile_table_streets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_table',
            name='downloadSpeed',
            field=models.CharField(default='', max_length=100),
        ),
    ]
