# Generated by Django 3.2.3 on 2021-05-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportApp', '0007_alter_profile_table_downloadspeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_table',
            name='uploadSpeed',
            field=models.CharField(default='', max_length=100),
        ),
    ]
