# Generated by Django 3.2.3 on 2021-05-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportApp', '0009_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='enable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availabilty', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
