# Generated by Django 3.2.3 on 2021-05-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportApp', '0010_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enable',
            name='availabilty',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
