# Generated by Django 3.2.3 on 2021-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webportApp', '0012_alter_enable_availabilty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enable',
            name='availabilty',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
